### PR TITLE
Complete GET API Routes

### LINKED ISSUE #13: Create API Endpoints

### PR DESCRIPTION
**Pull request by ajaygandecha**
This is a major pull request which completes the *fully-documented getter API Routes* for the final project.

## Major Changes
- Adds the following API Routes:
    - `GET /api/restaurants` - Retrieves all restaurants in the database.
    - `GET /api/restaurants/:id` - Retrieves a single restaurant from the database based on provided ID.
    - `GET /api/users/:id` - Retrieves a single user data from the database based on provided ID.
    - `GET /api/restaurant-reviews/:restaurantId` - Retrieves all reviews from the database based on provided restaurant ID.
    - `GET /api/user-reviews/:userId` - Retrieves all reviews from the databased based on provided user ID.

## What PR Does *not* Include

Not including a `GET` request to retrieve *all* reviews and *all* users is a deliberate choice. Data for all reviews is not important, and data for all users would not be secure.

## Future To-Dos

- Add `POST` API routes. This will be done once the POST `DataService` functions are completed.
- Add security to the `/api/users` API route so that unauthenticated users cannot call this API route.

*This PR resolves #13.*

### CODE REVIEW

**Comment by ajaygandecha** [comment]
Due to the merge, it shows more files being modified than there actually was. Once approved, I will fix the merge conflicts.

**Comment by zhangwy324** [comment]
Have you tested the `/restaurants` and `/restaurants/[id]` routes on the one restaurant data that we already have? If your test works as intended, it looks good.

**Comment by ajaygandecha** [comment]
@zhangwy324 yup it works as expected!

**Review by zhangwy324 — APPROVED** [review]
Looks good!

**Pull request merged**
