### PR TITLE
Add Post Data Service Functions

### LINKED ISSUE #12: Add Post functionality to DataService

### PR DESCRIPTION
**Pull request by ajaygandecha**
This pull request refactors `DataService` to include the *add functions* to add data to the Firebase Firestore database.

## Major Changes
- Added `createRestaurant`, `createUser`, and `createReview` functions to add data to the respective database collections.

*This PR resolves #12*

### CODE REVIEW

**Comment by zhangwy324** [comment]
With `createUser`, are we storing the user ID generated by Firebase authentication to the header id of the user document or to a field inside the document? If we are storing it as the header id of the document, how do we make sure that the id of the document is the same as the user ID generated by Firebase authentication?

Edit: When we create a new `user` document, is there a way to designate the document id instead of Firebase generating a random one for us?

**Comment by ajaygandecha** [comment]
Hi @zhangwy324 - yes, we can technically generate out own IDs when adding data into the database! If we were to do this we will need to come up with a way to generate this - either with hashing or auto increment.

If you think this would be better, we can try to do this!

**Comment by zhangwy324** [comment]
@ajaygandecha What I am saying is that when we create a new `user` document in our `users` collection, we should make the id of that document match the User UID generated by Firebase authentication. The process would be something like this:
1. A user logs in for the first time and Firebase generates a UID for this user
2. We check in our `users` collection for this UID
3. We do not find an existing user with this UID because it is this user's first time logging in
4. We create a user document with the UID using the `createUser` DataService method
5. Next time the user logs in, we check in our database and finds an existing `user` document with an ID of the current user's UID
6. We don't create a new user document this time. 

This is the process that I have in mind on the use case of the `createUser` method. I don't know if that is how you thought of it as well. Let me know. 

Edit:
Slight modification to the `authenticate` helper method to retrieve the user UID after signing in:
<pre>
const authenticate = async () => {
  const provider = new GoogleAuthProvider();
  const result = await signInWithPopup(auth, provider);
  const user = result.user;
  const uid = user.uid;
  if(!getUser(uid)){       // if this user is not found in Firestore, i.e. first time log in
    createUser(... , uid)  // create a user document that has document id same as uid
  }
};
</pre>

**Comment by ajaygandecha** [comment]
Hello @zhangwy324, the latest commit includes these changes and works as expected!

**Review by zhangwy324 — APPROVED** [review]
These changes are just what we needed! I tested it and it looks good!

**Pull request merged**
